# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='numpages',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
